[package]
authors = ["Andy Philpotts <andy@failfree.net>"]
edition = "2018"
name = "cobweb"
version = "0.1.0"
[dependencies]
anyhow = "*"
flexi_logger = "*"
log = "*"
scraper = "*"
argh = "*"

[dependencies.reqwest]
features = ["blocking"]
version = "*"
